#!/usr/bin/python3
import os
import sys
from os.path import dirname

if __name__ == '__main__':
    is_synthetic_linkage_call = False
    for arg in sys.argv:
        if arg.startswith('@rpath') and '_internal_linkage_SwiftPMImport' in arg:
            is_synthetic_linkage_call = True

    if is_synthetic_linkage_call:
        print(sys.argv)
        filelist_index = None
        platform_version = None
        arch = None
        output = None
        syslibroot = None
        dependency_info = None
        install_name = None

        for (index, arg) in enumerate(sys.argv[1:]):
            if arg == '-platform_version':
                platform_version = sys.argv[index + 2:index + 5]
            if arg == '-filelist':
                filelist_index = index + 2

            if arg == '-arch':
                arch = sys.argv[index + 2]
            if arg == '-o':
                output = sys.argv[index + 2]
            if arg == '-syslibroot':
                syslibroot = sys.argv[index + 2]
            if arg == '-dependency_info':
                dependency_info = sys.argv[index + 2]
            if arg == '-install_name' or arg == '-dylib_install_name':
                install_name = sys.argv[index + 2]
        if filelist_index is None:
            raise 'No filelist'

        filelist_path = sys.argv[filelist_index]
        empty_object_file = None
        with open(filelist_path, 'r') as file:
            for line in file:
                if '_internal_linkage_SwiftPMImport.o' in line:
                    empty_object_file = line
        if empty_object_file is None:
            raise f'Missing empty object file {filelist_path}'

        new_filelist = os.path.join(dirname(filelist_path), '_kotlinSwiftPMImport')
        with open(new_filelist, 'w') as file:
            file.write(empty_object_file)

        stub_ld_call = [
            "-dylib",
            "-dynamic",
            "-filelist", new_filelist,
            "-arch", arch,
            "-platform_version", *platform_version,
            "-syslibroot", syslibroot,
            "-dependency_info", dependency_info,
            "-install_name", install_name,
            "-lSystem",
            "-export_dynamic",
            "-o", output,
        ]
        print('ld ' + ' '.join([f'\'{arg}\'' for arg in stub_ld_call]))
        print(stub_ld_call)
        print(sys.argv)
        os.execlp('ld', 'ld', *stub_ld_call)
    else:
        os.execlp('ld', 'ld', *sys.argv[1:])
